# Generated by Django 5.0.1 on 2024-01-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='resume',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
